# Generated by Django 5.2.3 on 2025-06-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, upload_to='warket', verbose_name='Image'),
        ),
    ]
