# Generated by Django 5.2.3 on 2025-06-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='item',
            field=models.CharField(max_length=20),
        ),
    ]
