# Generated by Django 5.1.7 on 2025-09-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_group_type_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group_type_group',
            new_name='Categorylist',
        ),
    ]
