# Generated by Django 5.1.7 on 2025-09-21 06:37

from django.db import migrations, models

import items.models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_rename_group_type_group_categorylist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test", models.SlugField(verbose_name=items.models.Category)),
            ],
        ),
    ]
