# Generated by Django 5.2.3 on 2025-06-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_products_description_alter_products_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='currency',
            field=models.CharField(choices=[('$', '$'), ('₽', '₽'), ('€', '€')], default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(max_length=7),
        ),
    ]
