# Generated by Django 5.2.3 on 2025-06-28 19:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_products_currency_alter_products_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='model',
            field=models.CharField(choices=[('NEW', 'NEW'), ('SEC', 'SECONDHAND CAR'), ('FOR PARTS', 'FOR PARTS')], default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Some urgument'), django.core.validators.MaxValueValidator(1000000, message='Too much')]),
        ),
    ]
