# Generated by Django 5.1.7 on 2025-09-21 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_test"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
        migrations.AlterField(
            model_name="categorylist",
            name="category_slug",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_slug",
                to="items.category",
            ),
        ),
    ]
