# Generated by Django 5.2.3 on 2025-07-15 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_products_model_products_owner_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='currency',
            field=models.CharField(choices=[('$', '$')]),
        ),
        migrations.AlterField(
            model_name='products',
            name='item',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator('10'), django.core.validators.MaxLengthValidator('60')]),
        ),
    ]
