# Generated by Django 5.2.3 on 2025-07-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_products_currency_alter_products_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='item',
            field=models.CharField(),
        ),
    ]
