# Generated by Django 5.1.7 on 2025-09-22 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Category2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.categorylist'),
        ),
    ]
