# Generated by Django 5.1.7 on 2025-09-23 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0008_products_category2"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryChar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="items.category"
                    ),
                ),
            ],
        ),
    ]
