# Generated by Django 5.2.3 on 2025-07-15 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Some urgument'), django.core.validators.MaxValueValidator(1000000, message='Too much')]),
        ),
    ]
