# Generated by Django 5.2.3 on 2025-07-15 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(max_length=2, validators=[django.core.validators.MinValueValidator(1.0, message='Some urgument'), django.core.validators.MaxValueValidator(100000.0, message='Too much')]),
        ),
    ]
