# Generated by Django 5.2.3 on 2025-07-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_category_alter_cart_item_alter_cart_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField()),
            ],
        ),
    ]
