# Generated by Django 5.2.3 on 2025-08-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_rate_description_rate_produtc_rate_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='currency',
            field=models.CharField(choices=[('$', '$')], max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='item',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='model',
            field=models.CharField(choices=[('NEW', 'NEW'), ('SEC', 'SECONDHAND CAR'), ('FOR PARTS', 'FOR PARTS')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.CharField(choices=[('5', 5), ('4', 4), ('3', 3), ('2', 2), ('1', 1)], max_length=20),
        ),
    ]
