# Generated by Django 5.1.7 on 2025-08-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_alter_products_currency_alter_products_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='produtc',
            new_name='product',
        ),
    ]
