# Generated by Django 5.1.7 on 2025-08-07 17:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_rename_produtc_rate_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rate',
            new_name='ProductRate',
        ),
    ]
